import type { NextApiRequest, NextApiResponse } from 'next';
import { google } from 'googleapis';
import { sql } from '../../lib/db';

export const config = { maxDuration: 60 };

type SongResult = {
  position: number;
  song: string;
  artist: string;
  status: 'added' | 'not_found' | 'error';
  videoId?: string;
};

type ResponseData = {
  playlistId: string;
  playlistUrl: string;
  weekDate: string;
  total: number;
  added: number;
  skipped: number;
  results: SongResult[];
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData | { error: string }>
) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { refreshToken, chartName = 'Hot-100' } = req.body;

  if (!refreshToken) {
    return res.status(400).json({ error: 'refreshToken is required' });
  }

  const oauth2Client = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET
  );
  oauth2Client.setCredentials({ refresh_token: refreshToken });

  try {
    await oauth2Client.getAccessToken();
  } catch {
    return res.status(401).json({ error: 'YouTube session expired. Please re-authenticate.' });
  }

  const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

  // Fetch the most recent week of the requested chart
  const rows = await sql`
    SELECT artist, song, position, date
    FROM public.billboards
    WHERE chart = ${chartName}
      AND date = (SELECT MAX(date) FROM public.billboards WHERE chart = ${chartName})
    ORDER BY position
    LIMIT 100
  `;

  if (rows.length === 0) {
    return res.status(404).json({ error: `No entries found for chart: ${chartName}` });
  }

  const weekDate = rows[0].date as string;

  // Create the YouTube playlist
  const playlistRes = await youtube.playlists.insert({
    part: ['snippet', 'status'],
    requestBody: {
      snippet: {
        title: `Billboard ${chartName} — ${weekDate}`,
        description: `Billboard ${chartName} for the week of ${weekDate}. Auto-generated by Shadow Miracle Records.`,
      },
      status: { privacyStatus: 'public' },
    },
  });

  const playlistId = playlistRes.data.id!;
  const results: SongResult[] = [];

  // Search for each song in batches of 5 to stay within quota rate limits
  const BATCH_SIZE = 5;
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);

    const searched = await Promise.all(
      batch.map(async (row) => {
        try {
          const searchRes = await youtube.search.list({
            part: ['id'],
            q: `${row.song as string} ${row.artist as string}`,
            type: ['video'],
            videoCategoryId: '10', // Music
            maxResults: 1,
          });
          return {
            position: row.position as number,
            song: row.song as string,
            artist: row.artist as string,
            videoId: searchRes.data.items?.[0]?.id?.videoId ?? undefined,
          };
        } catch {
          return {
            position: row.position as number,
            song: row.song as string,
            artist: row.artist as string,
            videoId: undefined,
          };
        }
      })
    );

    // Insert found videos into the playlist in order
    for (const item of searched) {
      if (item.videoId) {
        try {
          await youtube.playlistItems.insert({
            part: ['snippet'],
            requestBody: {
              snippet: {
                playlistId,
                resourceId: { kind: 'youtube#video', videoId: item.videoId },
              },
            },
          });
          results.push({ ...item, status: 'added' });
        } catch {
          results.push({ ...item, status: 'error' });
        }
      } else {
        results.push({ ...item, status: 'not_found' });
      }
    }

    // Small pause between batches to avoid rate limiting
    if (i + BATCH_SIZE < rows.length) {
      await new Promise((r) => setTimeout(r, 200));
    }
  }

  const added = results.filter((r) => r.status === 'added').length;

  // Persist to DB so the public playlist page always shows the latest
  try {
    await sql`
      CREATE TABLE IF NOT EXISTS public.yt_playlists (
        id           SERIAL PRIMARY KEY,
        chart_name   TEXT        NOT NULL,
        week_date    TEXT        NOT NULL,
        playlist_id  TEXT        NOT NULL,
        playlist_url TEXT        NOT NULL,
        songs        JSONB,
        created_at   TIMESTAMPTZ DEFAULT NOW()
      )
    `;
    const playlistUrl = `https://www.youtube.com/playlist?list=${playlistId}`;
    const songsJson = JSON.stringify(results);
    await sql`
      INSERT INTO public.yt_playlists (chart_name, week_date, playlist_id, playlist_url, songs)
      VALUES (${chartName}, ${weekDate}, ${playlistId}, ${playlistUrl}, ${songsJson}::jsonb)
    `;
  } catch (saveErr) {
    console.error('Failed to save playlist to DB:', saveErr);
    // Non-fatal — playlist was still created on YouTube
  }

  return res.status(200).json({
    playlistId,
    playlistUrl: `https://www.youtube.com/playlist?list=${playlistId}`,
    weekDate,
    total: rows.length,
    added,
    skipped: rows.length - added,
    results,
  });
}
