import type { NextApiRequest, NextApiResponse } from 'next';
import { google } from 'googleapis';
import { sql } from '../../lib/db';

export const config = { maxDuration: 300 };

type PendingSong = { song: string; artist: string; peak_position: number; weeks_on_chart: number };

type SongResult = {
  position: number;
  song: string;
  artist: string;
  peakPosition: number;
  weeksOnChart: number;
  status: 'added' | 'not_found' | 'error';
  videoId?: string;
};

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { refreshToken, chartName = 'Hot-100', year } = req.body;
  if (!refreshToken) return res.status(400).json({ error: 'refreshToken is required' });
  if (!year || isNaN(Number(year))) return res.status(400).json({ error: 'year is required (e.g. 2025)' });
  const yearNum = Number(year);

  const oauth2Client = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET
  );
  oauth2Client.setCredentials({ refresh_token: refreshToken });
  try { await oauth2Client.getAccessToken(); }
  catch { return res.status(401).json({ error: 'YouTube session expired. Please re-authenticate.' }); }

  const youtube = google.youtube({ version: 'v3', auth: oauth2Client });

  const allRows = (await sql`
    SELECT
      song,
      artist,
      MIN(position)             AS peak_position,
      COUNT(DISTINCT date)::int AS weeks_on_chart
    FROM public.billboards
    WHERE chart = ${chartName}
      AND EXTRACT(YEAR FROM date::date) = ${yearNum}
    GROUP BY song, artist
    ORDER BY peak_position ASC, weeks_on_chart DESC
  `) as PendingSong[];

  if (allRows.length === 0) {
    return res.status(404).json({ error: `No data found for ${chartName} in ${yearNum}` });
  }

  // One playlist per chart+year: reuse the most complete existing one if it's still on YouTube
  const existing = (await sql`
    SELECT id, playlist_id, songs FROM public.yt_playlists
    WHERE chart_name = ${chartName} AND week_date = ${String(yearNum)}
    ORDER BY (SELECT count(*) FROM jsonb_array_elements(songs) s WHERE s->>'status' = 'added') DESC, created_at DESC
    LIMIT 1
  `) as { id: number; playlist_id: string; songs: SongResult[] | null }[];

  let rowId: number | null = null;
  let playlistId: string | null = null;
  const alreadyAdded = new Map<string, SongResult>();

  if (existing.length) {
    const check = await youtube.playlists.list({ part: ['id'], id: [existing[0].playlist_id] });
    if (check.data.items?.length) {
      rowId = existing[0].id;
      playlistId = existing[0].playlist_id;
      for (const s of existing[0].songs ?? []) {
        if (s.status === 'added') alreadyAdded.set(`${s.song}|||${s.artist}`, s);
      }
    }
  }

  if (!playlistId) {
    const playlistRes = await youtube.playlists.insert({
      part: ['snippet', 'status'],
      requestBody: {
        snippet: {
          title: `Billboard ${chartName} — All Songs of ${yearNum}`,
          description: `Every unique song that charted on Billboard ${chartName} in ${yearNum} (${allRows.length} total), ordered by peak position. Auto-generated by Shadow Miracle Records.`,
        },
        status: { privacyStatus: 'public' },
      },
    });
    playlistId = playlistRes.data.id!;
  }

  const results: SongResult[] = [];
  const toProcess: { row: PendingSong; position: number }[] = [];
  allRows.forEach((row, i) => {
    const prior = alreadyAdded.get(`${row.song}|||${row.artist}`);
    if (prior) {
      results.push({ ...prior, position: i + 1, peakPosition: row.peak_position, weeksOnChart: row.weeks_on_chart });
    } else {
      toProcess.push({ row, position: i + 1 });
    }
  });

  // Search 10 at a time for speed, stop gracefully if quota is exhausted
  const BATCH_SIZE = 10;
  let quotaExceeded = false;

  for (let i = 0; i < toProcess.length; i += BATCH_SIZE) {
    const chunk = toProcess.slice(i, i + BATCH_SIZE);

    const searched = await Promise.all(chunk.map(async ({ row, position }) => {
      const base = { position, song: row.song, artist: row.artist, peakPosition: row.peak_position, weeksOnChart: row.weeks_on_chart };
      if (quotaExceeded) return { ...base, videoId: undefined };
      try {
        const searchRes = await youtube.search.list({
          part: ['id'], q: `${row.song} ${row.artist}`,
          type: ['video'], videoCategoryId: '10', maxResults: 1,
        });
        return { ...base, videoId: searchRes.data.items?.[0]?.id?.videoId ?? undefined };
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : '';
        if (msg.includes('quota') || msg.includes('403')) quotaExceeded = true;
        return { ...base, videoId: undefined };
      }
    }));

    for (const item of searched) {
      if (item.videoId && !quotaExceeded) {
        try {
          await youtube.playlistItems.insert({
            part: ['snippet'],
            requestBody: { snippet: { playlistId, resourceId: { kind: 'youtube#video', videoId: item.videoId } } },
          });
          results.push({ ...item, status: 'added' });
        } catch (e: unknown) {
          const msg = e instanceof Error ? e.message : '';
          if (msg.includes('quota') || msg.includes('403')) quotaExceeded = true;
          results.push({ ...item, status: 'error' });
        }
      } else {
        results.push({ ...item, status: item.videoId ? 'not_found' : 'not_found' });
      }
    }

    if (quotaExceeded) {
      // Keep unprocessed songs in the list so a later run can pick them up
      for (const { row, position } of toProcess.slice(i + BATCH_SIZE)) {
        results.push({ position, song: row.song, artist: row.artist, peakPosition: row.peak_position, weeksOnChart: row.weeks_on_chart, status: 'not_found' });
      }
      break;
    }
  }

  results.sort((a, b) => a.position - b.position);
  const playlistUrl = `https://www.youtube.com/playlist?list=${playlistId}`;
  const songsJson = JSON.stringify(results);

  if (rowId !== null) {
    await sql`
      UPDATE public.yt_playlists
      SET songs = ${songsJson}::jsonb, status = 'complete', pending_songs = '[]'::jsonb
      WHERE id = ${rowId}
    `;
  } else {
    const saved = (await sql`
      INSERT INTO public.yt_playlists (chart_name, week_date, playlist_id, playlist_url, songs, status, pending_songs)
      VALUES (${chartName}, ${String(yearNum)}, ${playlistId}, ${playlistUrl}, ${songsJson}::jsonb, 'complete', '[]'::jsonb)
      RETURNING id
    `) as { id: number }[];
    rowId = saved[0].id;
  }

  return res.status(200).json({
    id: rowId,
    playlistId,
    playlistUrl,
    year: yearNum,
    chartName,
    totalSongs: allRows.length,
    added: results.filter(r => r.status === 'added').length,
    results,
    quotaExceeded,
  });
}
